package com.fire.sdk.model;

public enum Permission {
	PERM_BUSINESSES_GET_SERVICES,
    PERM_BUSINESSES_GET_ACCOUNTS,
    PERM_BUSINESSES_GET_ACCOUNT,
    PERM_BUSINESSES_GET_ACCOUNT_TRANSACTIONS,
    PERM_BUSINESSES_GET_ACCOUNT_TRANSACTIONS_FILTER,
    PERM_BUSINESSES_GET_FUNDING_SOURCES,
    PERM_BUSINESSES_GET_FUNDING_SOURCE,
    PERM_BUSINESSES_GET_FUNDING_SOURCE_TRANSACTIONS,
    PERM_BUSINESSES_GET_WEBHOOKS,
    PERM_BUSINESSES_GET_WEBHOOK_EVENT_TEST,
    PERM_BUSINESSES_GET_LIMITS,
    PERM_BUSINESSES_GET_FX_RATE,
    PERM_BUSINESSES_GET_APPS,
    PERM_BUSINESSES_GET_APP_PERMISSIONS,
    PERM_BUSINESSES_GET_APPS_PERMISSIONS,
    PERM_BUSINESSES_GET_WEBHOOK_TOKENS

}
